name: Create chris-kipp.io

on:
  push:
    branches:
      - main 

jobs:
  build:
    name: Make sure site can build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@main

      - name: Check formatting
        run: scala-cli format --check

      - name: Make sure it can build
        run: scala-cli run .
