name: Create chris-kipp.io

on:
  push:
    branches:
      - main 

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate site
        uses: docker://pandoc/core:2.13
        run: ./bin/make-site.sh
