name: Create chris-kipp.io

on:
  push:
    branches:
      - main 

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pandoc
        run: |
          sudo wget https://github.com/jgm/pandoc/releases/download/2.13/pandoc-2.13-1-amd64.deb
          sudo dpkg -i pandoc-2.13-1-amd64.deb

      - name: Generate Site
        run: ./bin/make-site.sh
