name: Create chris-kipp.io

on:
  push:
    branches:
      - main 

jobs:
  build:
    name: Make sure site can build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1.3.0
        with:
          apps: scala-cli

      - name: Make sure it can build
        run: scala-cli run src/
