name: Create chris-kipp.io

on:
  push:
    branches:
      - main 

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pandoc
        run: |
          sudo wget https://github.com/jgm/pandoc/releases/download/2.13/pandoc-2.13-1-amd64.deb
          sudo dpkg -i pandoc-2.13-1-amd64.deb

      - name: setup scala-cli
        uses: coursier/setup-action@v1.3.0
        with:
          apps: scala-cli

      - name: Generate Site
        run: ./bin/make-site.sh

      - name: Deploy Site
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./site
          vercel-args: '--prod'
